// Copyright 2019 Sic Studios. All rights reserved.
// Use of this source code is governed by our license that can be
// found in the LICENSE file.

#ifndef CAMERA_INFO_COMP_
#define CAMERA_INFO_COMP_

// Represents a camera.
struct Camera {
        vec4 position;
        vec4 direction;
        float focal_length;
        float width;
        float height;
        uint x_res;
        uint y_res;
};

#endif // CAMERA_INFO_COMP_