// Copyright 2019 Sic Studios. All rights reserved.
// Use of this source code is governed by our license that can be
// found in the LICENSE file.

#ifndef LIGHT_INFO_COMP_
#define LIGHT_INFO_COMP_

// Represents a Light.
struct Light {
    vec3 pow;
    vec3 pos;
    vec3 norm;
    float angle;
    uint type;
};

// Represents a sample of a light.
struct LightSample {
    vec3 dir;
    vec3 pow;
    float pdf, t;
};

#endif // LIGHT_INFO_COMP_